"""add_learning_fields_and_learning_logs_table

Revision ID: 8786cdcd3fa3
Revises: cdb85a01f46b
Create Date: 2026-06-07 19:01:09.576026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8786cdcd3fa3'
down_revision: Union[str, Sequence[str], None] = 'cdb85a01f46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_learning_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.Enum('auto', 'manual', name='enum_learning_trigger_type'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial_success', 'failed', 'aborted', name='enum_learning_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('tables_processed', sa.Integer(), nullable=True),
    sa.Column('columns_described', sa.Integer(), nullable=True),
    sa.Column('l0_count', sa.Integer(), nullable=True),
    sa.Column('l1_count', sa.Integer(), nullable=True),
    sa.Column('l2_count', sa.Integer(), nullable=True),
    sa.Column('l2_llm_calls', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('metadata_columns', sa.Column('semantic_description', sa.Text(), nullable=True))
    op.add_column('metadata_columns', sa.Column('description_source', sa.String(length=30), nullable=True))
    op.add_column('metadata_columns', sa.Column('description_confidence', sa.Float(), nullable=True))
    op.add_column('metadata_columns', sa.Column('detected_enum_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('metadata_columns', sa.Column('null_ratio', sa.Float(), nullable=True))
    op.add_column('metadata_columns', sa.Column('numeric_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('metadata_foreign_keys', 'target_column',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('metadata_tables', sa.Column('semantic_description', sa.Text(), nullable=True))
    op.add_column('metadata_tables', sa.Column('description_source', sa.String(length=30), nullable=True))
    op.add_column('metadata_tables', sa.Column('description_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_tables', 'description_confidence')
    op.drop_column('metadata_tables', 'description_source')
    op.drop_column('metadata_tables', 'semantic_description')
    op.alter_column('metadata_foreign_keys', 'target_column',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('metadata_columns', 'numeric_range')
    op.drop_column('metadata_columns', 'null_ratio')
    op.drop_column('metadata_columns', 'detected_enum_values')
    op.drop_column('metadata_columns', 'description_confidence')
    op.drop_column('metadata_columns', 'description_source')
    op.drop_column('metadata_columns', 'semantic_description')
    op.drop_table('metadata_learning_logs')
    # ### end Alembic commands ###
