"""create metadata tables

Revision ID: cdb85a01f46b
Revises: 2855855924af
Create Date: 2026-06-05 17:51:40.112721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdb85a01f46b'
down_revision: Union[str, Sequence[str], None] = '2855855924af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_sync_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('sync_type', sa.Enum('full', 'manual', name='enum_sync_type'), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='enum_sync_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('tables_added', sa.Integer(), nullable=True),
    sa.Column('tables_removed', sa.Integer(), nullable=True),
    sa.Column('columns_changed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('schema_name', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('table_type', sa.String(length=20), nullable=False),
    sa.Column('table_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'schema_name', 'table_name', name='uq_metadata_tables_ds_schema_table')
    )
    op.create_table('metadata_change_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sync_log_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.Enum('table_added', 'table_removed', 'column_added', 'column_removed', 'column_modified', 'index_added', 'index_removed', 'fk_added', 'fk_removed', name='enum_change_type'), nullable=False),
    sa.Column('schema_name', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('object_name', sa.String(length=100), nullable=True),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_log_id'], ['metadata_sync_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_columns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('column_comment', sa.Text(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['metadata_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'column_name', name='uq_metadata_columns_table_column')
    )
    op.create_table('metadata_foreign_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('constraint_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('target_schema', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=False),
    sa.Column('target_column', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['metadata_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'constraint_name', name='uq_metadata_fks_table_constraint')
    )
    op.create_table('metadata_indexes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('index_name', sa.String(length=100), nullable=False),
    sa.Column('column_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['metadata_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'index_name', name='uq_metadata_indexes_table_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_indexes')
    op.drop_table('metadata_foreign_keys')
    op.drop_table('metadata_columns')
    op.drop_table('metadata_change_logs')
    op.drop_table('metadata_tables')
    op.drop_table('metadata_sync_logs')
    # ### end Alembic commands ###
